### ISSUE TITLE
DataBindingUtil类找不到报错

### ISSUE THREAD

**Issue by beilly** [kymjs/TheMVP#10]
DataBinding的时候，会报错。这是跟编译版本有关系吗？

/com.vcredit.zj.noplayer W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/databinding/DataBinderMapper;
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:31)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.vcredit.zj.base.view.AppDelegate.create(AppDelegate.java:45)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.vcredit.zj.base.presenter.ActivityPresenter.createBinding(ActivityPresenter.java:61)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.vcredit.zj.base.presenter.ActivityPresenter.onCreate(ActivityPresenter.java:53)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.vcredit.zj.living.main.presenter.LivingActivity.onCreate(LivingActivity.java:18)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.Activity.performCreate(Activity.java:6876)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.os.Looper.loop(Looper.java:158)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7237)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.databinding.DataBinderMapper" on path: DexPathList[[zip file "/data/app/com.vcredit.zj.noplayer-2/base.apk"],nativeLibraryDirectories=[/data/app/com.vcredit.zj.noplayer-2/lib/arm, /data/app/com.vcredit.zj.noplayer-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err: 	... 17 more
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err: 	Suppressed: java.lang.ClassNotFoundException: android.databinding.DataBinderMapper
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.Class.classForName(Native Method)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-10 11:31:51.151 20204-20204/com.vcredit.zj.noplayer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by ilimei** [comment]
他好多类都没提交

**Comment by kymjs** [comment]
首先，你要知道 Databinding 是什么  
其次，你要知道 Databinding 怎么生成类  
最后，请阅读 README
