### ISSUE TITLE
非常棒的封装，不过有些疑惑

### ISSUE THREAD

**Issue by vihuela** [kymjs/TheMVP#4]
因为近期一个已经完工的项目是传统的MVP写的，遇到过些问题，在寻求解决方案时就无意看到了你的项目，非常感谢你提供如此棒的写法，但有些问题想请教你：
       demo的view和model绑定的使用场景是什么？在没用dataBinding时，那玩意和早年c# wpf很像，不完善暂时不用。

**Comment by kymjs** [comment]
界面的复杂度，有些时候一个界面实在复杂，即使把UI和逻辑分开两个类写依旧会写出七八百行的代码，这种时候，就可以把逻辑中根据不同场景对View设置不同内容的部分，单独出来使用数据绑定。  
最近在写一个相关的演示应用，大概等写完以后会开源。

**Comment by vihuela** [comment]
get it，我今天有在研究，刚刚写了下，很有意思，就是常规的recyclerView下拉刷新，在一个ViewDeligate中，然后放在activity或者fragment都可以，我觉得这是我最大的收获，不过ViewDeligate 中下拉控件的下拉刷新回调怎样和处于presenter的activity或者fragment交互最合适，因为ViewDeligate 中就是显示而已，难道activity或者fragment要拿到下拉控件的引用然后在外部设置回调？
       期待你的解答和后续更完善的例子。^_^

**Comment by kymjs** [comment]
可以看下这个项目  https://github.com/kymjs/CodeCafe

**Comment by LeoYe168** [comment]
果然都是中国人。。哈啊哈
