### ISSUE TITLE
ActivityPresenter需要设计些程序入口么？

### ISSUE THREAD

**Issue by json988** [kymjs/TheMVP#6]
ActivityPresenter需要设计些程序入口么？
比如有些在查找view之后的
和查找view之前的 一些程序初始化的入口？
还是说直接加入到bindEvenListener之中呢？
顺道问句 小哥有没有已经使用TheMVP开发的实例呢～～我正在使用开发一款app中～希望可以借鉴下

**Comment by kymjs** [comment]
你可以直接在onCreate里写啊

可以看看这个  https://github.com/kymjs/CodeCafe

**Comment by json988** [comment]
太感谢了～～～很好的实验案例
